title: GeoServer ACL
description: GeoServer Access Control List admin and authorization
show_downloads: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"
  
# Build settings
theme: minima

  